### ISSUE TITLE
Issues in almost-finished german file

### ISSUE THREAD

**Issue by Olfi01** [Pixelmon/Pixelmon-Language#403]
There are stil some issues with the german version, although most of the translation is complete, but now, if you add this language file, some strings are too big in order to fit inside their boxes. What could we do about this? Will we have to use abbreviations? Or maybe the coders can do something about it?

**Comment by Olfi01** [comment]
**EDIT:** Fixed almost all of those issues, only problem left: I just can't shorten the pokédex descriptions, maybe the coders could decrease the font size?

**Comment by Olfi01** [comment]
I've got the answer that this is impossible due to rendering issues, well, I guess (almost) nobody will care. Who reads those descriptions anyway?

**Comment by Keopha** [comment]
Us :p

Télécharger Outlook pour Android<https://aka.ms/ghei36>



On Mon, Sep 12, 2016 at 3:18 PM +0200, "Olfi01" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've got the answer that this is impossible due to rendering issues, well, I guess (almost) nobody will care. Who reads those descriptions anyway?

-

**Comment by Olfi01** [comment]
So, because nobody wrote anything new into this issue I'm gonna close it.
