### ISSUE TITLE
Trainer Editor

### ISSUE THREAD

**Issue by Olfi01** [Pixelmon/Pixelmon-Language#404]
I know, it's nothing really important, but someone should know.
Even if you're playing in german, the names of random generated pokémon in the npc editor menu for the traders are still in english. Maybe it's possible to fix this, maybe it's not. It's not that bad after all, 'cause if you enter the german names instead of the english ones, it'll work anyway. Just wanted to make sure somebody knows.

**Comment by Keopha** [comment]
Same in French


________________________________
De : Olfi01 <notifications@github.com>
Envoyé : vendredi 9 septembre 2016 10:31
À : Pixelmon/Pixelmon-Language
Objet : [Pixelmon/Pixelmon-Language] Trainer Editor (#404)


I know, it's nothing really important, but someone should know.
Even if you're playing in german, the names of random generated pokémon in the npc editor menu for the traders are still in english. Maybe it's possible to fix this, maybe it's not. It's not that bad after all, 'cause if you enter the german names instead of the english ones, it'll work anyway. Just wanted to make sure somebody knows.

-

**Comment by AnonymousRandomPerson** [comment]
Fixed.

**Comment by Olfi01** [comment]
Great, thanks!
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.

Am 09.09.2016, 17:39, AnonymousRandomPerson <notifications@github.com> schrieb:

Fixed.
